---
- hosts: all
  become: yes
  tasks:
    - name: install web server
      apt:
        name: apache2
        state: present

    - name: start service
      service:
        name: apache2
        state: started

    - name: copy the index file in webserver
      template:
        src: index.j2
        dest: /var/www/html/index.html
